### ISSUE TITLE
Could you please offer your code about Image Data?

### ISSUE THREAD

**Issue by junjie1003** [aniquetahir/GAIA#1]
I'm interested in your experiment about CelebA dataset in the image domain. Could you provide the corresponding code for me to reproduce the results mentioned in the paper?

**Comment by aniquetahir** [comment]
I will clean up the system specific information in the code and upload it over the weekend. Unfortunately, there is a lot of spaghetti code due to crunch.

**Comment by aniquetahir** [comment]
Added new code.
